#!/usr/bin/env ruby

require_relative 'sudoku_solver'

if ARGV.empty?
  puts "Usage: "
  puts "\t./solver file_path"

  exit 0
end

file_name = ARGV.shift

sudoku = Sudoku.from_file(file_name)

solver = SudokuSolver.new(sudoku)
solution = solver.solve

puts solution
